### ISSUE TITLE
Unrecognized field "total_including_tax" (class com.dtone.dvs.dto.Amount)

### ISSUE THREAD

**Issue by FE-hallen** [dtone/dtone-dvs-api-java-client#12]
Hello, it seems like at some point a new property was added to Amount, "total_including_tax", but this client wasn't updated to match.

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "total_including_tax" (class com.dtone.dvs.dto.Amount), not marked as ignorable (3 known properties: "total_excluding_tax", "base", "promotion_bonus"]) at [Source: org.apache.http.client.entity.LazyDecompressingInputStream@6b9745d7; line: 1, column: 174] (through reference chain: java.util.ArrayList[0]->com.dtone.dvs.dto.Product["benefits"]->java.util.ArrayList[0]->com.dtone.dvs.dto.Benefit["amount"]->com.dtone.dvs.dto.Amount["total_including_tax"])

**Comment by mohdhallal** [comment]
Hello @FE-hallen , `2.0.0` has been released with some major updates. Kindly take a look.
