### ISSUE TITLE
Unrecognized field "retail" (class com.dtone.dvs.dto.Rates)

### ISSUE THREAD

**Issue by fbunget** [dtone/dtone-dvs-api-java-client#4]
Hi,
it seems there's a new property "retail" in dto.Rates

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "retail" (class com.dtone.dvs.dto.Rates), not marked as ignorable (3 known properties: "discount_from_base", "base", "wholesale"])

Found it in Product ID: 14299

```
"id": 14299,
    "name": "100 DZD",
    "operator": {
      "country": {
        "iso_code": "DZA",
        "name": "Algeria",
        "regions": null
      },
      "id": 4,
      "name": "Mobilis Algeria",
      "regions": null
    },
...
"rates": {
      "base": 107.52688172043,
      "retail": 90.9090909090909,
      "wholesale": 107.52688172043
    },
```

**Comment by mohdhallal** [comment]
hello @fbunget , this is acknowledged, thanks for reporting.

@selvakumar-suyambulingam , heads up

**Comment by mohdhallal** [comment]
@fbunget apologies for missing this thread, hope you got the notification of the fix. Closing this issue.
